markdown: kramdown
permalink: 	 pretty

sass:
  style: compressed

defaults:
-
  scope:
    path: "2D" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "project-page"
    author: "Vertex Cat"
    permalink: "/:title"
-
  scope:
    path: "3D" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "project-page"
    author: "Vertex Cat"
    permalink: "/:title"

gems: 
- jekyll-haml
