markdown: kramdown
permalink: 	 pretty

sass:
  style: compressed

collections: 
  3D-flat:
    output: true
  3D-painted:
    output: true
  3D-sculpt:
    output: true
  2D-work:
    output: true
  
defaults:
-
  scope:
    path: "2D" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "project-page"
    author: "Vertex Cat"
    permalink: "/:title"
-
  scope:
    path: "3D" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "project-page"
    author: "Vertex Cat"
    permalink: "/:title"

gems: 
- jekyll-sitemap # must include here even with Gemfile 

jekyll-minifier: 
  remove_intertag_spaces: true
