markdown: kramdown
permalink: 	 pretty
sass:
  style: compressed

gems:
  - jemoji

defaults:
-
  scope:
    path: "2D" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "project-page"
    author: "Crista Alejandre"
    permalink: "/:title"
-
  scope:
    path: "3D" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "project-page"
    author: "Crista Alejandre"
    permalink: "/:title"
-
  scope:
    path: "blog" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "blog-post"
    author: "Crista Alejandre"
    permalink: "/blog/:title"